# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/absalom',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/absalom',
                'lib_path': 'absalom'},
  'syms': {'absalom.core': {'absalom.core.foo': ('core.html#foo', 'absalom/core.py')}}}
